INSERT INTO Allergene VALUES ("Coca Cola", "Colorant E211")
INSERT INTO Allergene VALUES ("Coca Light", "Colorant E211")
INSERT INTO Allergene VALUES ("Sprite", "Colorant E211")
INSERT INTO Allergene VALUES ("Fanta", "Colorant E211")
INSERT INTO Allergene VALUES ("Orangina", "")
INSERT INTO Allergene VALUES ("Ice Tea", "")
INSERT INTO Allergene VALUES ("Ice Tea Pêche", "")
INSERT INTO Allergene VALUES ("Schweppes Tonic", "")
INSERT INTO Allergene VALUES ("Schweppes Agrumes", "")
INSERT INTO Allergene VALUES ("Oasis", "")
INSERT INTO Allergene VALUES ("Cécémel", "Lactose  Histamine")
INSERT INTO Allergene VALUES ("Sirop à l'eau", "")
INSERT INTO Allergene VALUES ("Red Bull", "")
INSERT INTO Allergene VALUES ("Jus de fruit", "")
INSERT INTO Allergene VALUES ("Eau Spa", "")
INSERT INTO Allergene VALUES ("Eau Spa Pétillante", "")
INSERT INTO Allergene VALUES ("Eau San Pellegrino 50cl", "")
INSERT INTO Allergene VALUES ("Café Petit", "Histamine")
INSERT INTO Allergene VALUES ("Café Grand", "Histamine")
INSERT INTO Allergene VALUES ("Café Crème Petit", "Lactose  Histamine")
INSERT INTO Allergene VALUES ("Café Crème Grand", "Lactose  Histamine")
INSERT INTO Allergene VALUES ("Cappucino", "Lactose  Histamine")
INSERT INTO Allergene VALUES ("Café Décaféiné", "Histamine")
INSERT INTO Allergene VALUES ("Thé", "")
INSERT INTO Allergene VALUES ("Chocolat Chaud", "Lactose  Histamine")
INSERT INTO Allergene VALUES ("Jupiler 25cl", "Gluten")
INSERT INTO Allergene VALUES ("Jupiler 33cl", "Gluten")
INSERT INTO Allergene VALUES ("Jupiler 50cl", "Gluten")
INSERT INTO Allergene VALUES ("Leffe Blonde", "Gluten")
INSERT INTO Allergene VALUES ("Leffe Brune", "Gluten")
INSERT INTO Allergene VALUES ("Hoegarden Blanche", "Gluten")
INSERT INTO Allergene VALUES ("Hoegarden Rosée", "Gluten")
INSERT INTO Allergene VALUES ("Carlsberg", "Gluten")
INSERT INTO Allergene VALUES ("Bush 12° Ambrée", "Gluten")
INSERT INTO Allergene VALUES ("Leffe Triple", "Gluten")
INSERT INTO Allergene VALUES ("Chimay Bleue", "Gluten")
INSERT INTO Allergene VALUES ("Cuvée des Trolls", "Gluten")
INSERT INTO Allergene VALUES ("Desperados", "Gluten")
INSERT INTO Allergene VALUES ("Gueuze Belle Vue", "Gluten")
INSERT INTO Allergene VALUES ("Tripel Karmeliet", "Gluten")
INSERT INTO Allergene VALUES ("Lindemans Pêche", "Gluten")
INSERT INTO Allergene VALUES ("Rochefort 8°", "Gluten")
INSERT INTO Allergene VALUES ("Rochefort 10°", "Gluten")
INSERT INTO Allergene VALUES ("Westmalle Triple", "Gluten")
INSERT INTO Allergene VALUES ("Val Dieu Triple", "Gluten")
INSERT INTO Allergene VALUES ("Chouffe", "Gluten")
INSERT INTO Allergene VALUES ("Orval", "Gluten")
INSERT INTO Allergene VALUES ("Duvel", "Gluten")
INSERT INTO Allergene VALUES ("Gauloise Blonde", "Gluten")
INSERT INTO Allergene VALUES ("Gauloise Ambrée", "Gluten")
INSERT INTO Allergene VALUES ("Gauloise Brune", "Gluten")
INSERT INTO Allergene VALUES ("Pastis Ricard", "Lactose")
INSERT INTO Allergene VALUES ("Martini", "Sulfite")
INSERT INTO Allergene VALUES ("Martini Royale", "Sulfite")
INSERT INTO Allergene VALUES ("Campari", "Carmine")
INSERT INTO Allergene VALUES ("Pisang", "Histamine")
INSERT INTO Allergene VALUES ("Porto", "Sulfite")
INSERT INTO Allergene VALUES ("Pineau des Charentes", "Sulfite")
INSERT INTO Allergene VALUES ("Picon", "Colorant E150b")
INSERT INTO Allergene VALUES ("Kir Sauvignon", "Sulfite")
INSERT INTO Allergene VALUES ("Kir Royal", "Sulfite")
INSERT INTO Allergene VALUES ("Mojito", "")
INSERT INTO Allergene VALUES ("Cuba Libre", "")
INSERT INTO Allergene VALUES ("Bloody Mary", "Céleri")
INSERT INTO Allergene VALUES ("Margarita", "Agave")
INSERT INTO Allergene VALUES ("Get 27", "")
INSERT INTO Allergene VALUES ("Grappa", "")
INSERT INTO Allergene VALUES ("Vodka", "Gluten")
INSERT INTO Allergene VALUES ("Gin", "Amande")
INSERT INTO Allergene VALUES ("Bacardi", "")
INSERT INTO Allergene VALUES ("Bailey's", "Lactose  Arachides")
INSERT INTO Allergene VALUES ("Tequila", "Agave")
INSERT INTO Allergene VALUES ("William Lawson", "Gluten")
INSERT INTO Allergene VALUES ("Jack Daniel's", "Gluten")
INSERT INTO Allergene VALUES ("Amaretto", "Amande")
INSERT INTO Allergene VALUES ("Cognac", "")
INSERT INTO Allergene VALUES ("Calvados", "")
INSERT INTO Allergene VALUES ("Cointreau", "")
INSERT INTO Allergene VALUES ("Limoncello", "")
INSERT INTO Allergene VALUES ("Blanc Verre", "Sulfite")
INSERT INTO Allergene VALUES ("Blanc 1/4", "Sulfite")
INSERT INTO Allergene VALUES ("Blanc 1/2", "Sulfite")
INSERT INTO Allergene VALUES ("Blanc Bouteille", "Sulfite")
INSERT INTO Allergene VALUES ("Rosé Verre", "Sulfite")
INSERT INTO Allergene VALUES ("Rosé 1/4", "Sulfite")
INSERT INTO Allergene VALUES ("Rosé 1/2", "Sulfite")
INSERT INTO Allergene VALUES ("Rosé Bouteille", "Sulfite")
INSERT INTO Allergene VALUES ("Rouge Verre", "Sulfite  Histamine")
INSERT INTO Allergene VALUES ("Rouge 1/4", "Sulfite  Histamine")
INSERT INTO Allergene VALUES ("Rouge 1/2", "Sulfite  Histamine")
INSERT INTO Allergene VALUES ("Rouge Bouteille", "Sulfite  Histamine")
