INSERT INTO Allergene VALUES ("Cécémel", "Lactose");
INSERT INTO Allergene VALUES ("Café Crème Petit", "Lactose");
INSERT INTO Allergene VALUES ("Café Crème Grand", "Lactose");
INSERT INTO Allergene VALUES ("Cappucino", "Lactose");
INSERT INTO Allergene VALUES ("Chocolat Chaud", "Lactose");
INSERT INTO Allergene VALUES ("Pastis Ricard", "Lactose");
INSERT INTO Allergene VALUES ("Martini", "Sulfite");
INSERT INTO Allergene VALUES ("Martini Royale", "Sulfite");
INSERT INTO Allergene VALUES ("Campari", "Carmine");
INSERT INTO Allergene VALUES ("Porto", "Sulfite");
INSERT INTO Allergene VALUES ("Pineau des Charentes", "Sulfite");
INSERT INTO Allergene VALUES ("Picon", "Colorant");
INSERT INTO Allergene VALUES ("Picon", "E150b");
INSERT INTO Allergene VALUES ("Kir Sauvignon", "Sulfite");
INSERT INTO Allergene VALUES ("Kir Royal", "Sulfite");
INSERT INTO Allergene VALUES ("Bloody Mary", "Céleri");
INSERT INTO Allergene VALUES ("Margarita", "Agave");
INSERT INTO Allergene VALUES ("Gin", "Amande");
INSERT INTO Allergene VALUES ("Bailey's", "Lactose");
INSERT INTO Allergene VALUES ("Bailey's", "Arachides");
INSERT INTO Allergene VALUES ("Tequila", "Agave");
INSERT INTO Allergene VALUES ("Amaretto", "Amande");
